#! /usr/bin/python
import argparse

from pyqemulog import get_pql

if __name__ == '__main__':
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('arch', help='architecture', choices=['aarch32', 'mips32'])
    parser.add_argument('endian', help='endianness', choices=['little', 'big'])
    parser.add_argument('parse', help='parse lines of log', metavar='path/to/log')

    args = parser.parse_args()

    pql = get_pql(args.arch, args.endian, args.parse)
    pql.load_cpurf()
    pql.load_in_asm()
