#! /usr/bin/python
from pyqemulog import *

cpurfs = load_cpurf('log.txt', dump=False)
bbs = load_in_asm('log.txt', dump=False)

cpurf = cpurfs[39]
assert cpurf['ln'] == 510, cpurf
assert get_bb(cpurf, bbs)['in'] == '00008d80'
assert get_last_cpurf(cpurf, cpurfs)['ln'] == 494
assert get_last_bb(cpurf, cpurfs, bbs)['in'] == '00008e1c'
assert get_next_cpurf(cpurf, cpurfs)['ln'] == 529
assert get_next_bb(cpurf, cpurfs, bbs)['in'] == '00000010'
assert get_exception_return_cpurf(cpurf, cpurfs)['ln'] == 9997
assert get_exception_return_cpurf(cpurf, cpurfs)['exception']['pc'] == '0xDEADBEEF'
