#! /usr/bin/python
from pyqemulog import *

cpurfs = load_cpurf('log.txt', dump=False)
bbs = load_in_asm('log.txt', dump=False)

assert cpurfs[1]['exception']['type'] == 'switch', cpurf
cpurf = cpurfs[39]
assert cpurf['ln'] == 511, cpurf
assert get_bb(cpurf, bbs)['in'] == '00008d80'
assert get_last_cpurf(cpurf, cpurfs)['ln'] == 495
assert get_last_bb(cpurf, cpurfs, bbs)['in'] == '00008e1c'
assert get_next_cpurf(cpurf, cpurfs)['ln'] == 530
assert get_next_bb(cpurf, cpurfs, bbs)['in'] == '00000010'
assert get_exception_return_cpurf(cpurf, cpurfs)['ln'] == 9998
assert get_exception_return_cpurf(cpurf, cpurfs)['exception']['pc'] == '0xDEADBEEF'
