#! /usr/bin/python
from pyqemulog import *

cpurfs = load_cpurf('log.txt', dump=False)
bbs = load_in_asm('log.txt', dump=False)

# switch
assert cpurfs[1]['exception']['type'] == 'switch', cpurf
# irq
assert cpurfs[4]['exception']['type'] == 'irq'
# basic
cpurf = cpurfs[39]
assert cpurf['ln'] == 514, cpurf
assert get_bb(cpurf, bbs)['in'] == '00008d80'
assert get_last_cpurf(cpurf, cpurfs)['ln'] == 498
assert get_last_bb(cpurf, cpurfs, bbs)['in'] == '00008e1c'
assert get_next_cpurf(cpurf, cpurfs)['ln'] == 533
assert get_next_bb(cpurf, cpurfs, bbs)['in'] == '00000010'
assert get_exception_return_cpurf(cpurf, cpurfs)['ln'] == 10001
assert get_exception_return_cpurf(cpurf, cpurfs)['exception']['pc'] == '0xDEADBEEF'
